### PR TITLE
timeplot.cabal: tweak for Chart-1.7 (s/ChartBackend/BackendProgram/)

### PR DESCRIPTION
**Pull request by trofi**
Signed-off-by: Sergei Trofimovich <siarheit@google.com>

### CODE REVIEW

**Comment by jkff** [comment]
Sergei, it seems that the CI checks failed, could you take a look? (sorry for the late response, I'll respond faster next time)

**Comment by trofi** [comment]
Done.

Stack defaults to Chart-1.5 thus failed on constraint of Char >= 1.7.
As the change is only a type name change i've added alias to pre-1.7
type.

Now passes CI and builds fine on my system with Chart-1.7 and 1.8.

**Comment by tinkerware** [comment]
It would be great if you can release a new version so `cabal install` works.  `timeplot` looks really useful, thanks!

**Comment by jkff** [comment]
Done! Sorry for the delay.

**Pull request merged**
